import logging
import re
from dataclasses import dataclass

from software_factory_poc.core.application.agents.scaffolder.contracts.scaffolder_contracts import (
    ScaffoldingResponseSchema,
)
from software_factory_poc.core.application.ports import VcsPort
from software_factory_poc.core.application.skills.skill import BaseSkill
from software_factory_poc.core.domain.delivery import BranchName, CommitIntent, FileContent

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ApplyScaffoldDeliveryInput:
    """Input contract for the Git delivery step."""

    mission_key: str
    mission_summary: str
    branch_name: str
    target_branch: str
    scaffold_plan: ScaffoldingResponseSchema


class ApplyScaffoldDeliverySkill(BaseSkill[ApplyScaffoldDeliveryInput, str]):
    """Creates branch, commits files, and opens a Merge Request.

    Returns the MR web URL.
    """

    def __init__(self, vcs: VcsPort) -> None:
        self._vcs = vcs

    async def execute(self, input_data: ApplyScaffoldDeliveryInput) -> str:
        logger.info("[ApplyDelivery] Creating branch '%s'", input_data.branch_name)
        await self._vcs.create_branch(input_data.branch_name, ref=input_data.target_branch)

        intent = self._build_commit_intent(input_data.branch_name, input_data.scaffold_plan)
        logger.info("[ApplyDelivery] Committing %d files", len(intent.files))
        await self._vcs.commit_changes(intent)

        logger.info("[ApplyDelivery] Creating Merge Request")
        return await self._vcs.create_merge_request(
            source_branch=input_data.branch_name,
            target_branch=input_data.target_branch,
            title=f"feat: Scaffolding {input_data.mission_key}",
            description=f"Auto-generated by BrahMAS.\n\n{input_data.mission_summary}",
        )

    # ── Private helpers (moved from ScaffolderAgent) ──

    @staticmethod
    def build_branch_name(mission_key: str, service_name: str = "") -> str:
        """Build a deterministic, safe branch name from mission key."""
        safe_key = re.sub(r"[^a-z0-9\-]", "", mission_key.lower())
        if service_name:
            safe_service = re.sub(r"[^a-z0-9\-]", "-", service_name.lower().strip())
            return f"feature/{safe_key}-{safe_service}"
        return f"feature/{safe_key}-scaffolder"

    @staticmethod
    def _build_commit_intent(
        branch_name: str, scaffold_plan: ScaffoldingResponseSchema
    ) -> CommitIntent:
        """Convert the LLM response into a domain CommitIntent."""
        domain_files = [
            FileContent(path=f.path, content=f.content, is_new=f.is_new)
            for f in scaffold_plan.files
        ]
        return CommitIntent(
            branch=BranchName(value=branch_name),
            message=scaffold_plan.commit_message,
            files=domain_files,
        )
