import re
import logging
from typing import List
from software_factory_poc.application.core.domain.agents.common.dtos.file_content_dto import FileContentDTO
from software_factory_poc.infrastructure.observability.logger_factory_service import LoggerFactoryService

logger = LoggerFactoryService.build_logger(__name__)

class ArtifactParser:
    """
    Tool responsible for parsing the raw text response from the LLM 
    into structured FileContent objects.
    """

    def parse_response(self, response_text: str) -> List[FileContentDTO]:
        # content group captures everything until the END marker (handling empty body case)
        pattern = r"^\s*<<<FILE:\s*(?P<path>[\w./-]+)\s*>>>\s*\n(?P<content>.*?)\s*<<<END>>>"

        matches = re.finditer(pattern, response_text, re.MULTILINE | re.DOTALL)
        
        parsed_files: List[FileContentDTO] = []
        for match in matches:
             path = match.group("path").strip()
             content = match.group("content") or ""
             
             if ".." in path or path.startswith("/"):
                 logger.warning(f"Skipping invalid path: {path}")
                 continue
             
             if not content.strip():
                 content = "# Empty file generated by Scaffolding Agent"
                 
             parsed_files.append(FileContentDTO(path=path, content=content))
        
        return parsed_files
