import logging
from software_factory_poc.application.core.agents.scaffolding.value_objects.scaffolding_order import ScaffoldingOrder
from software_factory_poc.infrastructure.observability.logger_factory_service import LoggerFactoryService

logger = LoggerFactoryService.build_logger(__name__)

class ScaffoldingPromptBuilder:
    """
    Tool responsible for constructing the prompt for the Reasoner Agent.
    Encapsulates the prompt engineering logic.
    """

    def build_prompt(self, request: ScaffoldingOrder, knowledge_context: str) -> str:
        """
        Constructs the deterministic 'Super Prompt' for the LLM.
        """
        knowledge_context = self._validate_context(knowledge_context, request.issue_key)
        
        system_section = self._get_role_definition(request)
        context_section = self._format_rag_context(knowledge_context)
        task_section = self._format_task_instructions(request)
        example_section = self._get_example_output()

        full_prompt = f"{system_section}\n{context_section}\n{task_section}\n{example_section}"

        logger.info(f"--- [DEBUG] PROMPT GENERATED ({request.issue_key}) ---")
        return full_prompt

    def _validate_context(self, context: str, issue_key: str) -> str:
        if not context or not context.strip():
            logger.warning(f"Generating prompt for {issue_key} WITHOUT Knowledge Context (Empty RAG).")
            return "No specific architecture documentation provided. Use standard best practices."
        return context

    def _get_role_definition(self, request: ScaffoldingOrder) -> str:
        return (
            f"ROLE: You are an Expert Software Architect specializing in {request.technology_stack}.\n"
            f"MISSION: Create a production-ready 'Skeleton Scaffolding' for a project named '{request.issue_key}'.\n"
        )

    def _format_rag_context(self, context: str) -> str:
        return (
            f"--- ARCHITECTURAL STANDARDS (RAG CONTEXT) ---\n"
            f"{context}\n"
            f"----------------------------------------------\n"
        )

    def _format_task_instructions(self, request: ScaffoldingOrder) -> str:
        return (
            f"--- TASK INSTRUCTIONS ---\n"
            f"Project Name: {request.issue_key}\n"
            f"Tech Stack: {request.technology_stack}\n"
            f"User Summary: {request.summary}\n"
            f"Detailed Instructions: {request.raw_instruction}\n\n"
            f"--- CRITICAL OUTPUT RULES ---\n"
            f"1. **Configuration Files**: Generate FULL content for gitignore, package.json/requirements.txt, Dockerfile, etc.\n"
            f"2. **Structure Only**: Do NOT generate business logic. Create folders and place a 'README.md' inside each architectural layer explaining its purpose.\n"
            f"3. **Format**: You MUST return a STRICT JSON list of objects. Do not wrap in markdown.\n"
            f"   [\n"
            f"     {{\"path\": \"path/to/file.ext\", \"content\": \"...file content...\"}},\n"
            f"     ...\n"
            f"   ]\n"
        )

    def _get_example_output(self) -> str:
        return (
            f"--- EXAMPLE OUTPUT ---\n"
            f"[\n"
            f"  {{\"path\": \"README.md\", \"content\": \"# Project\\nGenerated by Software Factory.\"}},\n"
            f"  {{\"path\": \"src/main.py\", \"content\": \"print('Hello World')\"}}\n"
            f"]\n"
        )
