import logging
from software_factory_poc.application.core.agents.scaffolding.value_objects.scaffolding_order import ScaffoldingOrder
from software_factory_poc.infrastructure.observability.logger_factory_service import LoggerFactoryService

logger = LoggerFactoryService.build_logger(__name__)

class ScaffoldingPromptBuilder:
    """
    Tool responsible for constructing the prompt for the Reasoner Agent.
    Encapsulates the prompt engineering logic.
    """

    def build_prompt(self, request: ScaffoldingOrder, knowledge_context: str) -> str:
        """
        Constructs the deterministic 'Super Prompt' for the LLM.
        """
        # Validation / Diagnostics
        if not knowledge_context or not knowledge_context.strip():
            logger.warning(f"Generating prompt for {request.issue_key} WITHOUT Knowledge Context (Empty RAG).")
            knowledge_context = "No specific architecture documentation provided. Use standard best practices."

        # 1. System Persona & Role
        system_section = (
            f"ROLE: You are an Expert Software Architect specializing in {request.technology_stack}.\n"
            f"MISSION: Create a production-ready 'Skeleton Scaffolding' for a project named '{request.issue_key}'.\n"
        )

        # 2. Context (RAG)
        context_section = (
            f"--- ARCHITECTURAL STANDARDS (RAG CONTEXT) ---\n"
            f"{knowledge_context}\n"
            f"----------------------------------------------\n"
        )

        # 3. Task & Restrictions
        task_section = (
            f"--- TASK INSTRUCTIONS ---\n"
            f"Project Name: {request.issue_key}\n"
            f"Tech Stack: {request.technology_stack}\n"
            f"User Summary: {request.summary}\n"
            f"Detailed Instructions: {request.raw_instruction}\n\n"
            
            f"--- CRITICAL OUTPUT RULES ---\n"
            f"1. **Configuration Files**: Generate FULL content for gitignore, package.json/requirements.txt, Dockerfile, etc.\n"
            f"2. **Structure Only**: Do NOT generate business logic. Create folders and place a 'README.md' inside each architectural layer explaining its purpose.\n"
            f"3. **Format**: You MUST return a STRICT JSON list of objects. Do not wrap in markdown.\n"
            f"   [\n"
            f"     {{\"path\": \"path/to/file.ext\", \"content\": \"...file content...\"}},\n"
            f"     ...\n"
            f"   ]\n"
        )

        # 4. One-Shot Example (to enforce format)
        example_section = (
            f"--- EXAMPLE OUTPUT ---\n"
            f"[\n"
            f"  {{\"path\": \"README.md\", \"content\": \"# Project\\nGenerated by Software Factory.\"}},\n"
            f"  {{\"path\": \"src/main.py\", \"content\": \"print('Hello World')\"}}\n"
            f"]\n"
        )

        # Combine
        full_prompt = f"{system_section}\n{context_section}\n{task_section}\n{example_section}"

        # Debug Logging
        logger.info(f"--- [DEBUG] FULL GENERATED PROMPT ({request.issue_key}) ---\n{full_prompt}\n--- [END PROMPT] ---")

        return full_prompt
