import re

from software_factory_poc.application.core.ports.gateways.dtos import FileContent
from software_factory_poc.infrastructure.observability.logger_factory_service import (
    LoggerFactoryService,
)

logger = LoggerFactoryService.build_logger(__name__)


class FileParsingService:
    @staticmethod
    def parse_llm_response(response_text: str) -> list[FileContent]:
        """
        Parses LLM response using deterministic regex to extract file paths and content.
        Pattern: <<<FILE:path>>>...content...<<<END>>>
        """
        files = []
        # ^\s* matches start of line with optional whitespace
        # <<<FILE:\s* matches marker with optional whitespace
        # [\w./-]+ matches path
        # \s*>>> matches trailing whitespace and closing bracket
        # content group captures everything until the END marker (handling empty body case)
        pattern = r"^\s*<<<FILE:\s*(?P<path>[\w./-]+)\s*>>>\s*\n(?P<content>.*?)\s*<<<END>>>"

        matches = re.finditer(pattern, response_text, re.MULTILINE | re.DOTALL)
        
        parsed_files: list[FileContent] = []
        for match in matches:
             path = match.group("path").strip()
             content = match.group("content") or ""
             
             if ".." in path or path.startswith("/"):
                 logger.warning(f"Skipping invalid path: {path}")
                 continue
             
             if not content.strip():
                 content = "# Empty file generated by Scaffolding Agent"
                 
             parsed_files.append(FileContent(path=path, content=content))
        
        return parsed_files
