from software_factory_poc.application.core.domain.entities.scaffolding.scaffolding_request import ScaffoldingRequest
from software_factory_poc.infrastructure.observability.logger_factory_service import LoggerFactoryService

logger = LoggerFactoryService.build_logger(__name__)

class PromptBuilderService:
    """
    Constructs the deterministic 'Super Prompt' for the LLM, integrating 
    architectural context (RAG) and specific user instructions.
    """

    @staticmethod
    def build_scaffolding_prompt(request: ScaffoldingRequest, knowledge_context: str) -> str:
        """
        Builds the complete prompt string combining System Persona, Context, and Task.
        Logs the full prompt for debugging purposes.
        """
        
        # Validation / Diagnostics
        if not knowledge_context or not knowledge_context.strip():
            logger.warning(f"Generating prompt for {request.issue_key} WITHOUT Knowledge Context (Empty RAG).")
            knowledge_context = "No specific architecture documentation provided. Use standard best practices."

        # 1. System Persona & Role
        system_section = (
            f"ROLE: You are an Expert Software Architect specializing in {request.technology_stack}.\n"
            f"MISSION: Create a production-ready 'Skeleton Scaffolding' for a project named '{request.issue_key}'.\n"
        )

        # 2. Context (RAG)
        context_section = (
            f"--- ARCHITECTURAL STANDARDS (RAG CONTEXT) ---\n"
            f"{knowledge_context}\n"
            f"----------------------------------------------\n"
        )

        # 3. Task & Restrictions
        task_section = (
            f"--- TASK INSTRUCTIONS ---\n"
            f"Project Name: {request.issue_key}\n"
            f"Tech Stack: {request.technology_stack}\n"
            f"User Summary: {request.summary}\n"
            f"Detailed Instructions: {request.raw_instruction}\n\n"
            
            f"--- CRITICAL OUTPUT RULES ---\n"
            f"1. **Configuration Files**: Generate FULL content for gitignore, package.json/requirements.txt, Dockerfile, etc.\n"
            f"2. **Structure Only**: Do NOT generate business logic. Create folders and place a 'README.md' inside each architectural layer explaining its purpose.\n"
            f"3. **Format**: You MUST use the following format for every file. Do not use Markdown code blocks for the format itself.\n"
            f"   <<<FILE:path/to/file.ext>>>\n"
            f"   ...file content...\n"
            f"   <<<END>>>\n"
        )

        # 4. One-Shot Example (to enforce format)
        example_section = (
            f"--- EXAMPLE OUTPUT ---\n"
            f"<<<FILE:README.md>>>\n"
            f"# Project {request.issue_key}\n"
            f"Generated by Software Factory.\n"
            f"<<<END>>>\n"
            f"<<<FILE:src/main.py>>>\n"
            f"print('Hello World')\n"
            f"<<<END>>>\n"
        )

        # Combine
        full_prompt = f"{system_section}\n{context_section}\n{task_section}\n{example_section}"

        # 5. Debug Logging
        logger.info(f"--- [DEBUG] FULL GENERATED PROMPT ({request.issue_key}) ---\n{full_prompt}\n--- [END PROMPT] ---")

        return full_prompt
